voiceLines = [
"Alright! Which one of you's got great aim, and is good at chin scritches?",
"Cats make great companions! Just ask my master... who disappeared under mysterious circumstances.",
"Who's ready to risk our lives, defeat our foes, and maybe knock over some cups?" ,
"Tell me the game plan again. Wait. Fish! Someone has fish! Where is it?" ,
"So, who wants to be my best friend? ...Book, I know you're already my best friend!",
"Keep an eye out for red dot, Book! It's gotta be here somewhere.",
"Where's my fishy fishy fish for my dishy dishy dish?",
"Where's my fishy fish fish dish? Meow!",
"I won't lose you, Book! Not after losing Master.",
"Today we are destroyers!",
"Don't tell anyone but... I love hugs.",
"Book, float us that-a-way!",
"Where to, Book?",
"The expert huntress stalks the battlefield.",
"A river? Uh-uh! Book hates water!",
"Do not drop me! Do not drop me!",
"This way! No THIS way! Woah-kay, that way it is.",
"I'm like your ghost! WooOOooh!",
"They aren't ready for the ferocious team of... US!",
"You can pet me on my chin and back! Nowhere else. Mrow.",
"Do you have snacks in your pocket? How 'bout now? ...How 'bout now?!",
"Faster! Faster!",
"Is it time to save our friends again?",
"Ooh, you smell good! Did you recently fish?",
"Mush, mush! Wheeeeheehee!",
"I could tell you wanted a brave and powerful warrior by your side.",
"Do you ever get so sleepy you fall asleep sitting up? Just me?",
"Okay, it's time to prowl! You do know how to prowl, right?",
"Rubbing my head on you means you're mine!",
"If we find a rat, I call dibs! Or a bug. Or a FISH!",
"Wherever you go, I go! Just... don't go somewhere bad.",
"Naps make my magic stronger! It's true! Look! I'm so strong, mmh, so strong!",
"Hey Book, do you ever take a nap? ...You can't?! What do you do all day?!",
"Book, sometimes I pretend you're just a nice comfy box! ...What? That's a compliment!",
"The Book-keeper is a great role for someone as responsible as me! ...What?",
"I save my friends? No one notices. I open a teensy portal to the spirit realm? Everyone is up in my fur!",
"If I didn't have to protect Book, I'd just be a normal magical cat floating around Bandle City! Okay, napping around Bandle City.",
"I've read all of Book. Well, most of Book. I like the pictures of fish... of which there are none, Book!",
"Ah, I miss the way my yordle scratched between my ears. ...Being read from cover to cover sounds nice too.",
"Hmm, today should I follow my head? Or my nose, or.. OH! Sunbeam ahead! Let's chase that!",
"Someone scratched out the page that led here! That's right, Book. Someone! We'll never know who.",
"If I ever lost you, Book, the fabric of the spirit realm would get all torn up! And I'd lose my best friend.",
"I'm descended from lions! And you're descended from trees! We're in our element, Book!",
"The only thing standing between us and lunch is... our enemies.",
"I am the brains, you are the brawn, Book... is Book!",
"In case you're wondering what that smell is, it's Book. Smells like old trees.",
"Don't worry, I'll be here through thick or thin! Unless I smell fish. Gasp- Do you have fish?!",
"Hey, new friend? Uh, warn me if you're going to do something crazy, okay?",
"Don't get too attached, Book! This one looks reckless...",
"Hey. Hey. Hey. HEY! ...Huh? Oh no, I don't need anything!",
"You hungry? I stuck a leftover rat on page 237! Mew!",
"Do you know what \"vexatious\" means? Book called me that and I think it might be mean.",
"If someone told you to jump in a lake, would you do it? Just 'cause... I go where you go.",
"I bet we'll be friends forever! Well, unless you wander into the brush with your face."
]

sortedVoiceLines = [
    "I did it! I knocked it over!",
    "The only thing standing between us and lunch is... our enemies.",
    "Quick! Lay on your back and kick 'em.",
    "*auto attack*",
    "Book! Keep your light on!",
    "We did it! We knocked him over!",
    "Now you're ready to prowl.",
    "You hungry? I stuck a leftover rat on page 237. *meow*",
    "Book doesn't like you",
    "Yeah you birds can fly, well so can cats, this cat.",
    "Wow, even brighter than my shiny light!",
    "On to the next friend.",
    "Someone scratched out the page that led here, that's right book, someone. We'll never know who.",
    "Oo can I climb up on your spike thingies?",
    "Oh I am so knocking that over!",
    "Fishy fishy fish! Meow!",
    "I love keeping my friends alive.",
    "hah!",
    "*yuumi laughs* *yuumi coughs up a furball*",
    "Faster faster!",
    "Do you want me to bury that?",
    ""
    "Tell me the gameplan again. Wait, fish! Someone has fish! Where is it?",
    "*yuumi growls*",
    "You can't have book large metal cat!",
    "Wooooo",
    "Don't tell anyone but, I love hugs.",
    "Wherever you go, I go. Just, don't go somewhere bad.",
    "Do the bitey thing! Yeah that one!",
    "I'll stick with you!",
    "I hear you're red dot's master",
    "You're in bite range!",
    "Oo I thought we were playing! Are you dead?",
    "After this can you play the piano while I nap Jhin?",
    "Hey new friend, uh, warn me if you're gonna do something crazy ok?",
    "RAWR *yuumi coughs* excuse me",
    "I save my friends, no-one notices. I open a teensy portal to the spirit realm, everyone is up in my fur!",
    "*yuumi yawns* Is it time to save the world again?",
    "Make your shiny light glow Vel'Koz, I want to chase it!",
    "Tell me rengar, how do you groom all that fur?",
    "Let's slice 'em",
    "In case you're wondering what that smell is, it's book. Smells like old trees",
    "Hehe, they're never gonna see us coming!",
    "I've read all of book, well most of book. I like the pictures of fish, of which there are none book *sad meow*",
    "Spirit realm here we come!",
    "Woohoo! Now I can bat around the body!",
    "Ah I see you have the loud thing to scare off the enemy!",
    "Naps make my magic stronger. It's true! Look! *yuumi growls* I'm so strong, so strong.",
    "Attack pounce!",
    "Has there ever been a cat aspect Pantheon?",
    "Get ready to face the mighty Yuumi! Oh, and book.",
    "I'm like your ghost! Woooooooo.",
    "Do the secret five claw technique!",
    "This way! No this way! Woahhh ok that way it is!",
    "Hey! Kogmaw, I like coughing things up too! *yuumi coughs*",
    "I hiss at you giant pile of stones. Hiss!",
    "Yeah! What they said!",
    "I'm Yuumi and you're warm.",
    "Don't worry! I'll be here through thick or thin. Unless I smell fish. Do you have fish?",
    "The book keeper is a great role for someone as responsible as me! What?",
    "Where's my fishy fishy fish for my dishy dishy dish?",
    "Like a tiger!",
    "I bet we'll be friends forever. Well, unless you wander in to the brush with your face.",
    "*yuumi sighs* I miss the way my yordle scratched between my ears. Being read from cover to cover sounds nice too.",
    "I've got a good feeling about this one book!",
    "Wow, So you're in charge of the giant litter box huh bird guy.",
    "I guess we're going this away",
    "Ok, we can make this work.",
    "rawr",
    "If we find a rat I call dibs, or a bug OR A FISH. *yuumi hisses*",
    "Want a book thrown at your head? Don't worry book I would never do that. ",
    "The ol' pounce and scratch",
    "Teemo? I bet I can eat that guy, bet I can eat him",
    "Have you seen my master, she's about your size.",
    "Claws out!",
    "Ever pretend you're part of the floor? I do.",
    "They aren't ready for the ferocious team of, us",
    "We're killing buddies!",
    "*yuumi screams*",
    "Book meet new friend!",
    "Bop!",
    "Eugh, you smell like dog.",
    "Now kill 'em! Kill 'em!",
    "I'll protect you with my wild and furious, meow.",
    "You can pet me on my chin or back, nowhere else. *angry meow*",
    "Don't get too attached book, this one looks reckless",
    "Swat swat!",
    "Grrrr I'm a mountain lion!",
    "Use your claws! Your claws!",
    "Book, sometimes I pretend you are a nice comfy box. What? That's a compliment. prrrr",
    "It's ok, we've got 6 left, or was it 5?",
    "I have the best name in the spirit realm!",
    "*yuumi screams loudly*",
    "This is my favorite chapter!",
    "So does your gauntlet help you pet more cats?",
    "I bopped them all!",
    "*auto attack*",
    "Don't worry! Specters have nothing on magic cats.",
    "Book you got it backwards, you said Nasus was a god but he's just a dog.",
    "The expert huntress stalks the battle field",
    "We got the zoomies!",
    "I'm descended from lions and you're descended from trees! We're in our element book!",
    "Did someone say FISHbone?",
    "ZoooOOoom",
    "*yuumi yawns* is it time to save our friends again?",
    "Oo you're warm. Anyone smell burning fur?",
    "Do you know what vexatious means? Book called me that and I think it might be mean.",
    "I am the brains, you are the brawns, Book is book.",
    "Do not drop me! Do NOT drop me!",
    "Ok! It's time to prowl. You do know how to prowl right?",
    "I tried your thing book, now let's try my thing. Napping.",
    "Book float us thataway!",
    "I am totally doing this!",
    "Do you have snacks in your pocket? How 'bout now. How 'bout now?",
    "I am the most magic!",
    "A river? Uh uh, book hates water.",
    "Back on my own *meow*",
    "No no no! we can fix this!",
    "If I ever lost you book, the fabric of the spirit realm would get all torn up! And I'd lose my best friend.",
    "Squashed like a bug!",
    "We got this? We got this.",
    "I'm an independent cat.",
    "Cat's make great companions, just ask my master, who disappeared under mysterious circumstances.",
    "So, who wants to be my best friend. Book, I know you're already my best friend. ",
    "Book, meet giant scroll!",
    "Hey Book, do you ever take a nap, you can't? What do you do all day?",
    "Where to book? prrr",
    "If someone told you to jump in a lake, would you do it? Just cause, I go where you go?",
    "Hmm, today should I follow my head or my nose or oh! Sunbeam ahead let's chase that!",
    "*yuumi hisses* You look like unscratched furniture!",
    "My purr is louder than your growl dog",
    "The power of friendship!",
    "Oh wow hookman, someone who can actually fish!",
    "Mush, mush! Wheeeeheehee!",
    "So, you need a new shield buddy?",
    "Do you ever get so sleepy you fall asleep sitting up? Just me?",
    "Hang on book! I am hanging on!",
    "Watchout for us!",
    "Who's ready to risk our lives, defeat our foes and maybe knock over some cups",
    "I'm eat all your leaves and throw 'em up!",
    "You smell kinda like my Yordle",
    "Keep and eye out for red dot book, it's gotta be here somewhere",
    "Stupid overgrown scratching post",
    "Rubbing my head on your means you're mine prrr",
    "The red dot belongs to you!?",
    "Alright which one of you's got great aim and is good at chin scritches?",
    "Where's my fishy fish fish dish meow",
    "Oo you smell good, did you recently fish?",
    "Time to find a new friend!",
    "Cattack!",
    "Go go go go go go go!",
    "Today we are destoryers *yuumi laughts*",
    "Wooo! Here we gowowooowoowo!",
    "Ooh! Ooh! Get'em Ooh!",
    "Oh, so you're xayah's pet",
    "Ouch! See you in your next life!",
    "Just two cats, out on the town.",
    "Rats, I'm against them, extremely bad",
    "Well, this is embarrassing.",
    "Here fishy fishy fishy meow",
    "Book, what's happening to you?!",
    "Goodbye to the darkness!",
    "If I didn't have to protect book, I'd just be a normal magical cat floating around Bandle City, Ok, napping around Bandle City.",
    "Get your own book!",
    "I won't lose you book! Not after losing master.",
    "RAWR that's how bears talk",
    "We'll bite you!",
    "Hia!",
    "Scritchy scratch!",
    "It's just you and me book!",
    "*yuumi sniffs* You smell tasty!",
    "Hey hey hey HEY! Huh? Oh, no, I don't need anything.",
    "I love this parararart!",
    "I could tell you wanted a brave and powerful warrior by your side.",
]

dictVO = {
    "File0001.ogg" : "i did it i knocked it over",
    "File0002.ogg" : "the only thing standing between us and lunch is our enemies",
    "File0003.ogg" : "quick lay on your back and kick em",
    "File0004.ogg" : "auto attack",
    "File0005.ogg" : "book keep your light on",
    "File0006.ogg" : "we did it we knocked him over",
    "File0007.ogg" : "now youre ready to prowl",
    "File0008.ogg" : "you hungry i stuck a leftover rat on page 237 meow",
    "File0009.ogg" : "book doesnt like you",
    "File0010.ogg" : "yeah you birds can fly well so can cats this cat",
    "File0011.ogg" : "wow even brighter than my shiny light",
    "File0012.ogg" : "on to the next friend",
    "File0013.ogg" : "someone scratched out the page that led here thats right book someone well never know who",
    "File0014.ogg" : "oo can i climb up on your spike thingies",
    "File0015.ogg" : "oh i am so knocking that over",
    "File0016.ogg" : "fishy fishy fish meow",
    "File0017.ogg" : "i love keeping my friends alive",
    "File0018.ogg" : "hah",
    "File0019.ogg" : "yuumi laughs and coughs up a furball",
    "File0020.ogg" : "faster faster",
    "File0021.ogg" : "do you want me to bury that",
    "File0022.ogg" : "tell me the gameplan again wait fish someone has fish where is it",
    "File0023.ogg" : "yuumi growls",
    "File0024.ogg" : "you cant have book large metal cat",
    "File0025.ogg" : "wooooo",
    "File0026.ogg" : "dont tell anyone but i love hugs",
    "File0027.ogg" : "wherever you go i go just dont go somewhere bad",
    "File0028.ogg" : "do the bitey thing yeah that one",
    "File0029.ogg" : "ill stick with you",
    "File0030.ogg" : "i hear youre red dots master",
    "File0031.ogg" : "youre in bite range",
    "File0032.ogg" : "oo i thought we were playing are you dead",
    "File0033.ogg" : "after this can you play the piano while i nap jhin",
    "File0034.ogg" : "hey new friend uh warn me if youre gonna do something crazy ok",
    "File0035.ogg" : "rawr yuumi coughs excuse me",
    "File0036.ogg" : "i save my friends noone notices i open a teensy portal to the spirit realm everyone is up in my fur",
    "File0037.ogg" : "yuumi yawns is it time to save the world again",
    "File0038.ogg" : "make your shiny light glow velkoz i want to chase it",
    "File0039.ogg" : "tell me rengar how do you groom all that fur",
    "File0040.ogg" : "lets slice em",
    "File0041.ogg" : "in case youre wondering what that smell is its book smells like old trees",
    "File0042.ogg" : "hehe theyre never gonna see us coming",
    "File0043.ogg" : "ive read all of book well most of book i like the pictures of fish of which there are none book sad meow",
    "File0044.ogg" : "spirit realm here we come",
    "File0045.ogg" : "woohoo now i can bat around the body",
    "File0046.ogg" : "ah i see you have the loud thing to scare off the enemy",
    "File0047.ogg" : "naps make my magic stronger its true look yuumi growls im so strong so strong",
    "File0048.ogg" : "attack pounce",
    "File0049.ogg" : "has there ever been a cat aspect pantheon",
    "File0050.ogg" : "get ready to face the mighty yuumi oh and book",
    "File0051.ogg" : "im like your ghost woooooooo",
    "File0052.ogg" : "do the secret five claw technique",
    "File0053.ogg" : "this way no this way woahhh ok that way it is",
    "File0054.ogg" : "hey kogmaw i like coughing things up too yuumi coughs",
    "File0055.ogg" : "i hiss at you giant pile of stones hiss",
    "File0056.ogg" : "yeah what they said",
    "File0057.ogg" : "im yuumi and youre warm",
    "File0058.ogg" : "dont worry ill be here through thick or thin unless i smell fish do you have fish",
    "File0059.ogg" : "the book keeper is a great role for someone as responsible as me what",
    "File0060.ogg" : "wheres my fishy fishy fish for my dishy dishy dish",
    "File0061.ogg" : "like a tiger",
    "File0062.ogg" : "i bet well be friends forever well unless you wander in to the brush with your face",
    "File0063.ogg" : "yuumi sighs i miss the way my yordle scratched between my ears being read from cover to cover sounds nice too",
    "File0064.ogg" : "ive got a good feeling about this one book",
    "File0065.ogg" : "wow so youre in charge of the giant litter box huh bird guy",
    "File0066.ogg" : "i guess were going this away",
    "File0067.ogg" : "ok we can make this work",
    "File0068.ogg" : "rawr",
    "File0069.ogg" : "if we find a rat i call dibs or a bug or a fish yuumi hisses",
    "File0070.ogg" : "want a book thrown at your head dont worry book i would never do that ",
    "File0071.ogg" : "the ol pounce and scratch",
    "File0072.ogg" : "teemo i bet i can eat that guy bet i can eat him",
    "File0073.ogg" : "have you seen my master shes about your size",
    "File0074.ogg" : "claws out",
    "File0075.ogg" : "ever pretend youre part of the floor i do",
    "File0076.ogg" : "they arent ready for the ferocious team of us",
    "File0077.ogg" : "were killing buddies",
    "File0078.ogg" : "yuumi screams",
    "File0079.ogg" : "book meet new friend",
    "File0080.ogg" : "bop",
    "File0081.ogg" : "eugh you smell like dog",
    "File0082.ogg" : "now kill em kill em",
    "File0083.ogg" : "ill protect you with my wild and furious meow",
    "File0084.ogg" : "you can pet me on my chin or back nowhere else angry meow",
    "File0085.ogg" : "dont get too attached book this one looks reckless",
    "File0086.ogg" : "swat swat",
    "File0087.ogg" : "grrrr im a mountain lion",
    "File0088.ogg" : "use your claws your claws",
    "File0089.ogg" : "book sometimes i pretend you are a nice comfy box what thats a compliment prrrr",
    "File0090.ogg" : "its ok weve got 6 left or was it 5",
    "File0091.ogg" : "i have the best name in the spirit realm",
    "File0092.ogg" : "yuumi screams loudly",
    "File0093.ogg" : "this is my favorite chapter",
    "File0094.ogg" : "so does your gauntlet help you pet more cats",
    "File0095.ogg" : "i bopped them all",
    "File0096.ogg" : "auto attack",
    "File0097.ogg" : "dont worry specters have nothing on magic cats",
    "File0098.ogg" : "book you got it backwards you said nasus was a god but hes just a dog",
    "File0099.ogg" : "the expert huntress stalks the battle field",
    "File0100.ogg" : "we got the zoomies",
    "File0101.ogg" : "im descended from lions and youre descended from trees were in our element book",
    "File0102.ogg" : "did someone say fishbone",
    "File0103.ogg" : "zooooooom",
    "File0104.ogg" : "yuumi yawns is it time to save our friends again",
    "File0105.ogg" : "oo youre warm anyone smell burning fur",
    "File0106.ogg" : "do you know what vexatious means book called me that and i think it might be mean",
    "File0107.ogg" : "i am the brains you are the brawns book is book",
    "File0108.ogg" : "do not drop me do not drop me",
    "File0109.ogg" : "ok its time to prowl you do know how to prowl right",
    "File0110.ogg" : "i tried your thing book now lets try my thing napping",
    "File0111.ogg" : "book float us thataway",
    "File0112.ogg" : "i am totally doing this",
    "File0113.ogg" : "do you have snacks in your pocket how bout now how bout now",
    "File0114.ogg" : "i am the most magic",
    "File0115.ogg" : "a river uh uh book hates water",
    "File0116.ogg" : "back on my own meow",
    "File0117.ogg" : "no no no we can fix this",
    "File0118.ogg" : "if i ever lost you book the fabric of the spirit realm would get all torn up and id lose my best friend",
    "File0119.ogg" : "squashed like a bug",
    "File0120.ogg" : "we got this we got this",
    "File0121.ogg" : "im an independent cat",
    "File0122.ogg" : "cats make great companions just ask my master who disappeared under mysterious circumstances",
    "File0123.ogg" : "so who wants to be my best friend book i know youre already my best friend ",
    "File0124.ogg" : "book meet giant scroll",
    "File0125.ogg" : "hey book do you ever take a nap you cant what do you do all day",
    "File0126.ogg" : "where to book prrr",
    "File0127.ogg" : "if someone told you to jump in a lake would you do it just cause i go where you go",
    "File0128.ogg" : "hmm today should i follow my head or my nose or oh sunbeam ahead lets chase that",
    "File0129.ogg" : "yuumi hisses you look like unscratched furniture",
    "File0130.ogg" : "my purr is louder than your growl dog",
    "File0131.ogg" : "the power of friendship",
    "File0132.ogg" : "oh wow hookman someone who can actually fish",
    "File0133.ogg" : "mush mush wheeeeheehee",
    "File0134.ogg" : "so you need a new shield buddy",
    "File0135.ogg" : "do you ever get so sleepy you fall asleep sitting up just me",
    "File0136.ogg" : "hang on book i am hanging on",
    "File0137.ogg" : "watchout for us",
    "File0138.ogg" : "whos ready to risk our lives defeat our foes and maybe knock over some cups",
    "File0139.ogg" : "im eat all your leaves and throw em up",
    "File0140.ogg" : "you smell kinda like my yordle",
    "File0141.ogg" : "keep and eye out for red dot book its gotta be here somewhere",
    "File0142.ogg" : "stupid overgrown scratching post",
    "File0143.ogg" : "rubbing my head on your means youre mine prrr",
    "File0144.ogg" : "the red dot belongs to you",
    "File0145.ogg" : "alright which one of yous got great aim and is good at chin scritches",
    "File0146.ogg" : "wheres my fishy fish fish dish meow",
    "File0147.ogg" : "oo you smell good did you recently fish",
    "File0148.ogg" : "time to find a new friend",
    "File0149.ogg" : "cattack",
    "File0150.ogg" : "go go go go go go go",
    "File0151.ogg" : "today we are destoryers yuumi laughts",
    "File0152.ogg" : "wooo here we gowowooowoowo",
    "File0153.ogg" : "ooh ooh getem ooh",
    "File0154.ogg" : "oh so youre xayahs pet",
    "File0155.ogg" : "ouch see you in your next life",
    "File0156.ogg" : "just two cats out on the town",
    "File0157.ogg" : "rats im against them extremely bad",
    "File0158.ogg" : "well this is embarrassing",
    "File0159.ogg" : "here fishy fishy fishy meow",
    "File0160.ogg" : "book whats happening to you",
    "File0161.ogg" : "goodbye to the darkness",
    "File0162.ogg" : "if i didnt have to protect book id just be a normal magical cat floating around bandle city ok napping around bandle city",
    "File0163.ogg" : "get your own book",
    "File0164.ogg" : "i wont lose you book not after losing master",
    "File0165.ogg" : "rawr thats how bears talk",
    "File0166.ogg" : "well bite you",
    "File0167.ogg" : "hia",
    "File0168.ogg" : "scritchy scratch",
    "File0169.ogg" : "its just you and me book",
    "File0170.ogg" : "yuumi sniffs you smell tasty",
    "File0171.ogg" : "hey hey hey hey huh oh no i dont need anything",
    "File0172.ogg" : "i love this parararart",
    "File0173.ogg" : "i could tell you wanted a brave and powerful warrior by your side",
}