voiceLines = [
"Alright! Which one of you's got great aim, and is good at chin scritches?",
"Cats make great companions! Just ask my master... who disappeared under mysterious circumstances.",
"Who's ready to risk our lives, defeat our foes, and maybe knock over some cups?" ,
"Tell me the game plan again. Wait. Fish! Someone has fish! Where is it?" ,
"So, who wants to be my best friend? ...Book, I know you're already my best friend!",
"Keep an eye out for red dot, Book! It's gotta be here somewhere.",
"Where's my fishy fishy fish for my dishy dishy dish?",
"Where's my fishy fish fish dish? Meow!",
"I won't lose you, Book! Not after losing Master.",
"Today we are destroyers!",
"Don't tell anyone but... I love hugs.",
"Book, float us that-a-way!",
"Where to, Book?",
"The expert huntress stalks the battlefield.",
"A river? Uh-uh! Book hates water!",
"Do not drop me! Do not drop me!",
"This way! No THIS way! Woah-kay, that way it is.",
"I'm like your ghost! WooOOooh!",
"They aren't ready for the ferocious team of... US!",
"You can pet me on my chin and back! Nowhere else. Mrow.",
"Do you have snacks in your pocket? How 'bout now? ...How 'bout now?!",
"Faster! Faster!",
"Is it time to save our friends again?",
"Ooh, you smell good! Did you recently fish?",
"Mush, mush! Wheeeeheehee!",
"I could tell you wanted a brave and powerful warrior by your side.",
"Do you ever get so sleepy you fall asleep sitting up? Just me?",
"Okay, it's time to prowl! You do know how to prowl, right?",
"Rubbing my head on you means you're mine!",
"If we find a rat, I call dibs! Or a bug. Or a FISH!",
"Wherever you go, I go! Just... don't go somewhere bad.",
"Naps make my magic stronger! It's true! Look! I'm so strong, mmh, so strong!",
"Hey Book, do you ever take a nap? ...You can't?! What do you do all day?!",
"Book, sometimes I pretend you're just a nice comfy box! ...What? That's a compliment!",
"The Book-keeper is a great role for someone as responsible as me! ...What?",
"I save my friends? No one notices. I open a teensy portal to the spirit realm? Everyone is up in my fur!",
"If I didn't have to protect Book, I'd just be a normal magical cat floating around Bandle City! Okay, napping around Bandle City.",
"I've read all of Book. Well, most of Book. I like the pictures of fish... of which there are none, Book!",
"Ah, I miss the way my yordle scratched between my ears. ...Being read from cover to cover sounds nice too.",
"Hmm, today should I follow my head? Or my nose, or.. OH! Sunbeam ahead! Let's chase that!",
"Someone scratched out the page that led here! That's right, Book. Someone! We'll never know who.",
"If I ever lost you, Book, the fabric of the spirit realm would get all torn up! And I'd lose my best friend.",
"I'm descended from lions! And you're descended from trees! We're in our element, Book!",
"The only thing standing between us and lunch is... our enemies.",
"I am the brains, you are the brawn, Book... is Book!",
"In case you're wondering what that smell is, it's Book. Smells like old trees.",
"Don't worry, I'll be here through thick or thin! Unless I smell fish. Gasp- Do you have fish?!",
"Hey, new friend? Uh, warn me if you're going to do something crazy, okay?",
"Don't get too attached, Book! This one looks reckless...",
"Hey. Hey. Hey. HEY! ...Huh? Oh no, I don't need anything!",
"You hungry? I stuck a leftover rat on page 237! Mew!",
"Do you know what \"vexatious\" means? Book called me that and I think it might be mean.",
"If someone told you to jump in a lake, would you do it? Just 'cause... I go where you go.",
"I bet we'll be friends forever! Well, unless you wander into the brush with your face."
]

sortedVoiceLines = [
    "I did it! I knocked it over!",
    "The only thing standing between us and lunch is... our enemies.",
    "Quick! Lay on your back and kick 'em.",
    "*auto attack*",
    "Book! Keep your light on!",
    "We did it! We knocked him over!",
    "Now you're ready to prowl.",
    "You hungry? I stuck a leftover rat on page 237. *meow*",
    "Book doesn't like you",
    "Yeah you birds can fly, well so can cats, this cat.",
    "Wow, even brighter than my shiny light!",
    "On to the next friend.",
    "Someone scratched out the page that led here, that's right book, someone. We'll never know who.",
    "Oo can I climb up on your spike thingies?",
    "Oh I am so knocking that over!",
    "Fishy fishy fish! Meow!",
    "I love keeping my friends alive.",
    "hah!",
    "*yuumi laughs* *yuumi coughs up a furball*",
    "Faster faster!",
    "Do you want me to bury that?",
    ""
    "Tell me the gameplan again. Wait, fish! Someone has fish! Where is it?",
    "*yuumi growls*",
    "You can't have book large metal cat!",
    "Wooooo",
    "Don't tell anyone but, I love hugs.",
    "Wherever you go, I go. Just, don't go somewhere bad.",
    "Do the bitey thing! Yeah that one!",
    "I'll stick with you!",
    "I hear you're red dot's master",
    "You're in bite range!",
    "Oo I thought we were playing! Are you dead?",
    "After this can you play the piano while I nap Jhin?",
    "Hey new friend, uh, warn me if you're gonna do something crazy ok?",
    "RAWR *yuumi coughs* excuse me",
    "I save my friends, no-one notices. I open a teensy portal to the spirit realm, everyone is up in my fur!",
    "*yuumi yawns* Is it time to save the world again?",
    "Make your shiny light glow Vel'Koz, I want to chase it!",
    "Tell me rengar, how do you groom all that fur?",
    "Let's slice 'em",
    "In case you're wondering what that smell is, it's book. Smells like old trees",
    "Hehe, they're never gonna see us coming!",
    "I've read all of book, well most of book. I like the pictures of fish, of which there are none book *sad meow*",
    "Spirit realm here we come!",
    "Woohoo! Now I can bat around the body!",
    "Ah I see you have the loud thing to scare off the enemy!",
    "Naps make my magic stronger. It's true! Look! *yuumi growls* I'm so strong, so strong.",
    "Attack pounce!",
    "Has there ever been a cat aspect Pantheon?",
    "Get ready to face the mighty Yuumi! Oh, and book.",
    "I'm like your ghost! Woooooooo.",
    "Do the secret five claw technique!",
    "This way! No this way! Woahhh ok that way it is!",
    "Hey! Kogmaw, I like coughing things up too! *yuumi coughs*",
    "I hiss at you giant pile of stones. Hiss!",
    "Yeah! What they said!",
    "I'm Yuumi and you're warm.",
    "Don't worry! I'll be here through thick or thin. Unless I smell fish. Do you have fish?",
    "The book keeper is a great role for someone as responsible as me! What?",
    "Where's my fishy fishy fish for my dishy dishy dish?",
    "Like a tiger!",
    "I bet we'll be friends forever. Well, unless you wander in to the brush with your face.",
    "*yuumi sighs* I miss the way my yordle scratched between my ears. Being read from cover to cover sounds nice too.",
    "I've got a good feeling about this one book!",
    "Wow, So you're in charge of the giant litter box huh bird guy.",
    "I guess we're going this away",
    "Ok, we can make this work.",
    "rawr",
    "If we find a rat I call dibs, or a bug OR A FISH. *yuumi hisses*",
    "Want a book thrown at your head? Don't worry book I would never do that. ",
    "The ol' pounce and scratch",
    "Teemo? I bet I can eat that guy, bet I can eat him",
    "Have you seen my master, she's about your size.",
    "Claws out!",
    "Ever pretend you're part of the floor? I do.",
    "They aren't ready for the ferocious team of, us",
    "We're killing buddies!",
    "*yuumi screams*",
    "Book meet new friend!",
    "Bop!",
    "Eugh, you smell like dog.",
    "Now kill 'em! Kill 'em!",
    "I'll protect you with my wild and furious, meow.",
    "You can pet me on my chin or back, nowhere else. *angry meow*",
    "Don't get too attached book, this one looks reckless",
    "Swat swat!",
    "Grrrr I'm a mountain lion!",
    "Use your claws! Your claws!",
    "Book, sometimes I pretend you are a nice comfy box. What? That's a compliment. prrrr",
    "It's ok, we've got 6 left, or was it 5?",
    "I have the best name in the spirit realm!",
    "*yuumi screams loudly*",
    "This is my favorite chapter!",
    "So does your gauntlet help you pet more cats?",
    "I bopped them all!",
    "*auto attack*",
    "Don't worry! Specters have nothing on magic cats.",
    "Book you got it backwards, you said Nasus was a god but he's just a dog.",
    "The expert huntress stalks the battle field",
    "We got the zoomies!",
    "I'm descended from lions and you're descended from trees! We're in our element book!",
    "Did someone say FISHbone?",
    "ZoooOOoom",
    "*yuumi yawns* is it time to save our friends again?",
    "Oo you're warm. Anyone smell burning fur?",
    "Do you know what vexatious means? Book called me that and I think it might be mean.",
    "I am the brains, you are the brawns, Book is book.",
    "Do not drop me! Do NOT drop me!",
    "Ok! It's time to prowl. You do know how to prowl right?",
    "I tried your thing book, now let's try my thing. Napping.",
    "Book float us thataway!",
    "I am totally doing this!",
    "Do you have snacks in your pocket? How 'bout now. How 'bout now?",
    "I am the most magic!",
    "A river? Uh uh, book hates water.",
    "Back on my own *meow*",
    "No no no! we can fix this!",
    "If I ever lost you book, the fabric of the spirit realm would get all torn up! And I'd lose my best friend.",
    "Squashed like a bug!",
    "We got this? We got this.",
    "I'm an independent cat.",
    "Cat's make great companions, just ask my master, who disappeared under mysterious circumstances.",
    "So, who wants to be my best friend. Book, I know you're already my best friend. ",
    "Book, meet giant scroll!",
    "Hey Book, do you ever take a nap, you can't? What do you do all day?",
    "Where to book? prrr",
    "If someone told you to jump in a lake, would you do it? Just cause, I go where you go?",
    "Hmm, today should I follow my head or my nose or oh! Sunbeam ahead let's chase that!",
    "*yuumi hisses* You look like unscratched furniture!",
    "My purr is louder than your growl dog",
    "The power of friendship!",
    "Oh wow hookman, someone who can actually fish!",
    "Mush, mush! Wheeeeheehee!",
    "So, you need a new shield buddy?",
    "Do you ever get so sleepy you fall asleep sitting up? Just me?",
    "Hang on book! I am hanging on!",
    "Watchout for us!",
    "Who's ready to risk our lives, defeat our foes and maybe knock over some cups",
    "I'm eat all your leaves and throw 'em up!",
    "You smell kinda like my Yordle",
    "Keep and eye out for red dot book, it's gotta be here somewhere",
    "Stupid overgrown scratching post",
    "Rubbing my head on your means you're mine prrr",
    "The red dot belongs to you!?",
    "Alright which one of you's got great aim and is good at chin scritches?",
    "Where's my fishy fish fish dish meow",
    "Oo you smell good, did you recently fish?",
    "Time to find a new friend!",
    "Cattack!",
    "Go go go go go go go!",
    "Today we are destoryers *yuumi laughts*",
    "Wooo! Here we gowowooowoowo!",
    "Ooh! Ooh! Get'em Ooh!",
    "Oh, so you're xayah's pet",
    "Ouch! See you in your next life!",
    "Just two cats, out on the town.",
    "Rats, I'm against them, extremely bad",
    "Well, this is embarrassing.",
    "Here fishy fishy fishy meow",
    "Book, what's happening to you?!",
    "Goodbye to the darkness!",
    "If I didn't have to protect book, I'd just be a normal magical cat floating around Bandle City, Ok, napping around Bandle City.",
    "Get your own book!",
    "I won't lose you book! Not after losing master.",
    "RAWR that's how bears talk",
    "We'll bite you!",
    "Hia!",
    "Scritchy scratch!",
    "It's just you and me book!",
    "*yuumi sniffs* You smell tasty!",
    "Hey hey hey HEY! Huh? Oh, no, I don't need anything.",
    "I love this parararart!",
    "I could tell you wanted a brave and powerful warrior by your side.",
]